import org.jetbrains.kotlin.konan.target.Architecture
import org.jetbrains.kotlin.konan.target.Family
import org.jetbrains.kotlin.konan.util.visibleName

plugins {
    id("conventions.kotlin")
    id("conventions.testing")
    id("conventions.detekt")
    alias(libs.plugins.buildConfig)
}

kotlin {
    listOf(
        linuxX64(),
        linuxArm64(),
        macosArm64(),
    ).forEach { target ->
        target.compilations.getByName("main") {
            cinterops {
                val stbImage by creating {
                    val dir = project.file("src/nativeInterop/cinterop/stbImage")
                    definitionFile.set(dir.resolve("stb_image.def"))
                    packageName("stbImage")
                    compilerOpts("-I/${dir}")
                }
            }
        }
        target.binaries.executable {
            entryPoint = "${CompileOptions.GROUP}.cli.main"
            baseName = with(target.konanTarget) {
                val arch = when(architecture) {
                    Architecture.ARM64 -> "aarch64"
                    Architecture.X64 -> "x86_64"
                    else -> error("Unsupported architecture: $architecture")
                }
                val system = when(family) {
                    Family.LINUX -> "linux"
                    Family.OSX -> "darwin"
                    else -> error("Unsupported OS family: $family")
                }
                "steko-${arch}-${system}"
            }
        }
    }

    sourceSets {
        nativeMain.dependencies {
            implementation(project(":steko-core"))
            implementation(libs.kotlin.cryptography.optimalProvider)
            implementation(libs.kotlin.io.core)
            implementation(libs.kotlin.serialization.core)
            implementation(libs.kotlin.serialization.cbor)
            implementation(libs.clikt.core)
            implementation(libs.clikt.markdown)
        }
    }

    fixLinuxCompile()
}

buildConfig {
    packageName = CompileOptions.GROUP + ".cli"
    documentation = "Generated by build."

    buildConfigField("APP_VERSION", CompileOptions.VERSION)
}
